### ISSUE TITLE
MD Grid Implementation Might Be Questionable

### ISSUE THREAD

**Issue by peterpengwei** [breagen/MachSuite#9]
There might be an issue from the force update mechanism of the MD Grid implementation. Based on my understanding of MD, the new forces should all come out from the original input of the forces. However, the code implementation directly write the updated force to the original force vectors, leading to the fact that each force is calculated from some cells with updated forces and some cells with original forces. I was wondering if it is an issue on algorithm implementation.

**Comment by rdadolf** [comment]
Hi Peter,

The forces in MachSuite's MD codes are computed off the Lennard-Jones potential, which is derived from atom position, not other forces. We actually don't provide an outer loop for updating position information. Even in this case, however, the forces would be calculated in one phase, then the points would be updated in another.

I quickly read over the code again, and it looks correct to me. Going to close, but if I'm wrong, please reopen this.

Good to know other eyes are inspecting the code deeply. Thanks!
